# Generated by Django 5.1 on 2024-08-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='score1',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='score2',
            field=models.SmallIntegerField(default=0),
        ),
    ]
