# Generated by Django 5.1 on 2024-08-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0004_alter_match_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='games',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='points',
            field=models.SmallIntegerField(default=0),
        ),
    ]
