# Generated by Django 5.1 on 2024-08-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0005_alter_player_games_alter_player_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='point_balance',
            field=models.IntegerField(default=0),
        ),
    ]
