# Generated by Django 5.1 on 2024-08-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0008_alter_set_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='set_num',
            field=models.IntegerField(default=0),
        ),
    ]
