# Generated by Django 5.1 on 2024-08-23 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0010_finalsmatch_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='set_winner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_winner', to='table.player'),
        ),
    ]
