# Generated by Django 5.1 on 2024-08-26 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0011_set_set_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='table.finalsmatch'),
        ),
    ]
